config/routes.rb
Utopiaspora::Application.routes.draw do
  resources :profiles


  controller :publics do
    get '.well-known/host-meta' => :host_meta
  end


  ### up to now, default devise, but new session = sign_in should get 
  # own form with username instead of email
  #devise_for :users
  devise_for :users, :controllers => {
                                      :registrations => "registrations",
                                      :password      => "devise/passwords",
                                      :sessions      => "sessions",
                                    } do
                                     # :invitations   => "invitations"} do
#    get 'invitations/resend/:id' => 'invitations#resend', :as => 'invitation_resend'
#    get 'invitations/email' => 'invitations#email', :as => 'invite_email'
  end
 
  
  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'home#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/profile.rb
class Profile < ActiveRecord::Base

  
  attr_accessible :first_name, :last_name, :image_url, :image_url_medium,
    :image_url_small, :birthday, :gender, :bio, :location, :searchable, :date
  
  belongs_to :person

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.json
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(params[:profile])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render json: @profile, status: :created, location: @profile }
      else
        format.html { render action: "new" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :ok }
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.haml
= form_for @profile do |f|
  -if @profile.errors.any?
    #error_explanation
      %h2= "#{pluralize(@profile.errors.count, "error")} prohibited this profile from being saved:"
      %ul
        - @profile.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :diaspora_handle
    = f.text_field :diaspora_handle
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :image_url
    = f.text_field :image_url
  .field
    = f.label :image_url_small
    = f.text_field :image_url_small
  .field
    = f.label :image_url_medium
    = f.text_field :image_url_medium
  .field
    = f.label :birthday
    = f.date_select :birthday
  .field
    = f.label :gender
    = f.text_field :gender
  .field
    = f.label :bio
    = f.text_area :bio
  .field
    = f.label :searchable
    = f.check_box :searchable
  .field
    = f.label :person_id
    = f.number_field :person_id
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :full_name
    = f.text_field :full_name
  .actions
    = f.submit 'Save'

app/views/profiles/edit.html.haml
%h1 Editing profile

= render 'form'

= link_to 'Show', @profile
\|
= link_to 'Back', profiles_path

app/views/profiles/index.html.haml
%h1 Listing profiles

%table
  %tr
    %th Diaspora handle
    %th First name
    %th Last name
    %th Image url
    %th Image url small
    %th Image url medium
    %th Birthday
    %th Gender
    %th Bio
    %th Searchable
    %th Person
    %th Location
    %th Full name
    %th
    %th
    %th

  - @profiles.each do |profile|
    %tr
      %td= profile.diaspora_handle
      %td= profile.first_name
      %td= profile.last_name
      %td= profile.image_url
      %td= profile.image_url_small
      %td= profile.image_url_medium
      %td= profile.birthday
      %td= profile.gender
      %td= profile.bio
      %td= profile.searchable
      %td= profile.person_id
      %td= profile.location
      %td= profile.full_name
      %td= link_to 'Show', profile
      %td= link_to 'Edit', edit_profile_path(profile)
      %td= link_to 'Destroy', profile, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Profile', new_profile_path

app/views/profiles/new.html.haml
%h1 New profile

= render 'form'

= link_to 'Back', profiles_path

app/views/profiles/show.html.haml
%p#notice= notice

%p
  %b Diaspora handle:
  = @profile.diaspora_handle
%p
  %b First name:
  = @profile.first_name
%p
  %b Last name:
  = @profile.last_name
%p
  %b Image url:
  = @profile.image_url
%p
  %b Image url small:
  = @profile.image_url_small
%p
  %b Image url medium:
  = @profile.image_url_medium
%p
  %b Birthday:
  = @profile.birthday
%p
  %b Gender:
  = @profile.gender
%p
  %b Bio:
  = @profile.bio
%p
  %b Searchable:
  = @profile.searchable
%p
  %b Person:
  = @profile.person_id
%p
  %b Location:
  = @profile.location
%p
  %b Full name:
  = @profile.full_name

= link_to 'Edit', edit_profile_path(@profile)
\|
= link_to 'Back', profiles_path